export const ROUTE_HOME = '/contacts'
export const ROUTE_NEW_CONTACT = '/contacts/new'
export const ROUTE_NEW_CATEGORY = '/categories/new'
export const ROUTE_NEW_PRIORITY = 'priorities/new'
export const ROUTE_AUTH = '/'
